apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nodeport
  namespace: delivery
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: http
      nodePort: 30080
      name: http
