apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - catalog-service.yaml
  - fleet-service.yaml
  - order-service.yaml
  - api-gateway.yaml
  - api-gateway-nodeport.yaml
